[package]
name = "dynet"
description = "Command-line boundary for Dynet."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "dynet"
path = "src/main.rs"

[dependencies]
clap.workspace = true
dynet-api.workspace = true
plumb.workspace = true
