[package]
name = "dynet-api"
description = "Reusable API boundary for Dynet."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
name = "dynet_api"
path = "src/lib.rs"

[dependencies]
dynet-core.workspace = true
aes.workspace = true
aes-gcm.workspace = true
hmac.workspace = true
sha2.workspace = true
md-5.workspace = true
smoltcp.workspace = true

[dev-dependencies]
dynet-core.workspace = true
